Add multi layers support
JOSM/todo pull request #4
Opened 2017-08-19 19:47 UTC by bagage

Currently todo plugin does not support when you switch between layers. Say, for instance, you have data to check in layer *A*, and actual OSM data in layer *B*.
You add all objects from *A* in todo plugin, but you want to check that these data are present (or not) in OSM, so you switch to your work layer *B*.
Whenever you want to mark a todo item *done* or else, you have **to switch to layer A, do the action, and switch back to your work layer**. This PR aims to solve that issue.

This also add full support for multilayers todo items (if you want some items from layer A and some from layer B) - todolist item will now display the layer in bracket eg `node 1092 [layer A]`:

![image](https://user-images.githubusercontent.com/1451988/29489738-06b84aec-8528-11e7-91a8-f0a724013f8f.png)

2017-08-19 20:26 UTC, don-vip commented on src/org/openstreetmap/josm/plugins/todo/TodoDialog.java
> +        sel.forEach(primitive -> items.add(new TodoListItem(layer, primitive)));
could probably become a single statement, something like `return layer.data.getSelected().stream().map(...).collect(...);`

2017-08-19 20:28 UTC, don-vip commented on src/org/openstreetmap/josm/plugins/todo/TodoListModel.java
> +class TodoListItemRenderer implements ListCellRenderer<TodoListItem> {
can you please move each new class to its own file?

2017-08-19 20:29 UTC, bagage commented on src/org/openstreetmap/josm/plugins/todo/TodoListModel.java
> +class TodoListItemRenderer implements ListCellRenderer<TodoListItem> {
Yes, sure.

2017-08-19 20:30 UTC, don-vip commented on src/org/openstreetmap/josm/plugins/todo/TodoListModel.java
> +    public boolean equals(Object obj) {
please override hashCode if you override equals.

2017-08-19 20:31 UTC, don-vip requested changes
looks good, only few remarks to take into account :)

2017-08-19 21:08 UTC, bagage commented
Thanks for the quick review and the helpful tips @don-vip, I tweaked the PR accordingly. (not 100% sure about how I implemented `hashCode`, if you wish to check it).

2017-08-20 12:35 UTC, don-vip approved these changes

2017-08-20 12:36 UTC, merged

2017-08-20 12:36 UTC, don-vip commented
thanks a lot!